services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: furfolio
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: furfolio
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  minio:
    driver: local
