services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: furfolio
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: furfolio
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  s3:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - "minio:/data/minio"
    command: minio server /data/minio --console-address ":9090"

volumes:
  minio:
    driver: local