# Generated by Django 4.2.4 on 2023-09-08 00:22

from django.db import migrations, models
import furfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0003_offer_cutoff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cutoff_date',
            field=models.DateTimeField(default=furfolio.models.seven_days_from_now),
        ),
    ]
