# Generated by Django 4.2.4 on 2023-09-11 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0005_rename_created_date_offer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
