# Generated by Django 4.2.4 on 2023-09-13 22:20

import django.core.validators
from django.db import migrations, models
import furfolio.models
import furfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0006_alter_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cutoff_date',
            field=models.DateTimeField(default=furfolio.models.seven_days_from_now, validators=[furfolio.validators.validate_datetime_not_in_past, furfolio.validators.validate_datetime_at_least_12_hours]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(help_text='Must be between 5 and 80 characters long.', max_length=80, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
