# Generated by Django 4.2.4 on 2023-09-15 20:56

from django.db import migrations, models
import furfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0008_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatars are optional. Your avatar must be 64 by 64 pixels.', upload_to='', validators=[furfolio.validators.validate_profile_image_is_right_size]),
        ),
    ]
