# Generated by Django 4.2.4 on 2023-09-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0011_remove_commission_commissionee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='initial_request_text',
            field=models.TextField(default='', max_length=3760),
        ),
    ]
