# Generated by Django 4.2.4 on 2023-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0012_alter_commission_initial_request_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('CREATOR', 'Creator')], default='BUYER', help_text='Your role on this platform. This is used to optimize your experience and to let others know how you want to use this website.', max_length=7),
        ),
    ]
