# Generated by Django 4.2.4 on 2023-09-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0013_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='state',
            field=models.CharField(default='REVIEW', max_length=11),
        ),
    ]
