# Generated by Django 4.2.4 on 2023-09-23 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0014_commission_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commissioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
