# Generated by Django 4.2.4 on 2023-09-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0015_alter_commission_commissioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='forced_closed',
            field=models.BooleanField(default=False),
        ),
    ]
