# Generated by Django 4.2.4 on 2023-09-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0016_offer_forced_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='forced_closed',
            field=models.BooleanField(default=False, help_text='Indicates that the offer is closed, regardless if the cutoff date has passed or not.'),
        ),
    ]
