# Generated by Django 4.2.4 on 2023-09-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0017_alter_offer_forced_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='attachment',
            field=models.FileField(blank=True, help_text='Other files that are part of this request.', upload_to=''),
        ),
    ]
