# Generated by Django 4.2.4 on 2023-09-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0018_commission_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file that is part of this request.', upload_to=''),
        ),
    ]
