# Generated by Django 4.2.4 on 2023-09-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0019_alter_commission_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='initial_request_text',
            field=models.TextField(default='', help_text='First-pass requirements for the commission.', max_length=3760, verbose_name='Initial Requirements'),
        ),
    ]
