# Generated by Django 4.2.4 on 2023-09-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0027_alter_offer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='state',
            field=models.CharField(choices=[('REVIEW', 'Review'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='REVIEW', max_length=11),
        ),
    ]
