# Generated by Django 4.2.4 on 2023-09-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0028_alter_commission_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
