# Generated by Django 4.2.4 on 2023-09-29 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('furfolio', '0030_commissionmessage'), ('furfolio', '0031_alter_commissionmessage_commission'), ('furfolio', '0032_commissionmessage_id_and_more')]

    dependencies = [
        ('furfolio', '0029_commission_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionMessage',
            fields=[
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furfolio.commission')),
                ('message', models.TextField(max_length=1645)),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id', models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
