# Generated by Django 4.2.4 on 2023-09-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0029_commission_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionMessage',
            fields=[
                ('commission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='furfolio.commission')),
                ('message', models.TextField(max_length=1645)),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
