# Generated by Django 4.2.4 on 2023-09-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0030_commissionmessage_squashed_0032_commissionmessage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
