# Generated by Django 4.2.4 on 2023-10-01 00:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0035_alter_offer_cutoff_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=False, fields=['username'], name='user_username_index'),
        ),
    ]
