# Generated by Django 4.2.4 on 2023-10-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0038_alter_commission_state_alter_offer_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='state',
            field=models.CharField(choices=[('REVIEW', 'Review'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Finished'), ('REJECTED', 'Rejected')], default='REVIEW', max_length=11),
        ),
    ]
