# Generated by Django 4.2.4 on 2023-10-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0042_alter_offer_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='rating',
            field=models.CharField(choices=[('GEN', 'General'), ('ADL', 'Adult')], default='GEN', max_length=3),
        ),
    ]
