# Generated by Django 4.2.4 on 2023-10-13 23:44

import django.core.validators
from django.db import migrations, models
import furfolio.models
import furfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0043_alter_offer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cutoff_date',
            field=models.DateTimeField(default=furfolio.models.seven_days_from_now, validators=[furfolio.validators.validate_datetime_not_in_past, furfolio.validators.validate_datetime_is_not_over_year_into_future]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_review_commissions',
            field=models.PositiveIntegerField(default=5, help_text='The maximum number of commissions allowed to be in the review state.<br>Use this to prevent being overloaded with too many commission requests at a time for this offer.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Commissions in Review'),
        ),
    ]
