# Generated by Django 4.2.4 on 2023-10-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0044_alter_offer_cutoff_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('USD', 'United States Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_price',
            field=models.PositiveIntegerField(default=5, help_text='The maximum price for commissions of this offer.', verbose_name='Maximum Price'),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_price',
            field=models.PositiveIntegerField(default=0, help_text='The minimum price for commissions of this offer.', verbose_name='Minimum Price'),
        ),
    ]
