# Generated by Django 4.2.4 on 2023-10-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0045_offer_currency_offer_max_price_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('USD', '$ United States Dollar (USD)'), ('EUR', '€ Euro (EUR)')], default='USD', max_length=3),
        ),
    ]
