# Generated by Django 4.2.4 on 2023-10-20 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import furfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0047_user_consent_to_adult_content_alter_offer_max_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDescriptiveStrForCreator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('furfolio.offer',),
        ),
        migrations.AlterField(
            model_name='commission',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file that is part of this request.', upload_to='', validators=[furfolio.validators.validate_commission_attachment_has_max_size]),
        ),
        migrations.AlterField(
            model_name='commissionmessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='', validators=[furfolio.validators.validate_commission_message_attachment_has_max_size]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[furfolio.validators.validate_offer_thumbnail_aspect_ratio, furfolio.validators.validate_offer_thumbnail_has_max_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatars are optional. Your avatar must be 64 by 64 pixels.', upload_to='', validators=[furfolio.validators.validate_profile_image_is_right_size, furfolio.validators.validate_avatar_has_max_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='consent_to_adult_content',
            field=models.BooleanField(default=False, help_text='Indicate if you would like to see adult content on this website. If not indicated, you will not see adult content.<br> If you consent, you agree that you are legally allowed to view "adult" content.', verbose_name='Consent to see adult content'),
        ),
        migrations.CreateModel(
            name='UserFollowingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
