# Generated by Django 4.2.4 on 2023-10-23 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0048_offerdescriptivestrforcreator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="max_price",
            field=models.PositiveIntegerField(
                default=5,
                help_text="The maximum price for commissions of this offer.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000000000),
                ],
                verbose_name="Maximum Price",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="min_price",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The minimum price for commissions of this offer.",
                validators=[django.core.validators.MaxValueValidator(999999999)],
                verbose_name="Minimum Price",
            ),
        ),
    ]
