# Generated by Django 4.2.4 on 2023-10-23 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfolio', '0050_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='max_commissions_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Limits how many commissions a user can make on this offer. Self-managed commissions are not limited.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Commissions per User'),
        ),
    ]
