# Generated by Django 4.2.4 on 2023-10-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0052_alter_offer_max_review_commissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
