# Generated by Django 4.2.4 on 2023-11-06 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0055_auto_20231106_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
