# Generated by Django 4.2.4 on 2023-11-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0056_tag_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
