# Generated by Django 4.2.4 on 2023-11-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0057_tag_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=4700, verbose_name="Description"
            ),
        ),
    ]
