# Generated by Django 4.2.4 on 2023-11-08 17:22

from django.db import migrations


def add_tag_category_moderators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    tag_permissions = Permission.objects.filter(
        codename__in=[
            "add_tagcategory",
            "change_tagcategory",
            "delete_tagcategory",
            "view_tagcategory",
        ]
    )

    tag_cat_mod_group = Group(name="tag_cat_mods")
    tag_cat_mod_group.save()
    tag_cat_mod_group.permissions.set(tag_permissions)
    tag_cat_mod_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0060_alter_tag_author"),
    ]

    operations = [
        migrations.RunPython(add_tag_category_moderators_group),
    ]
