# Generated by Django 4.2.4 on 2023-11-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0061_auto_20231108_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagcategory",
            name="description",
            field=models.TextField(blank=True, default="", max_length=4700),
        ),
    ]
