# Generated by Django 4.2.4 on 2023-11-13 21:34

import django.core.validators
from django.db import migrations, models
import furfolio.models
import furfolio.validators


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0062_tagcategory_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="cutoff_date",
            field=models.DateTimeField(
                default=furfolio.models.seven_days_from_now,
                help_text="When your offer is no longer accepting commissions.",
                validators=[
                    furfolio.validators.validate_datetime_not_in_past,
                    furfolio.validators.validate_datetime_is_not_over_year_into_future,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="description",
            field=models.TextField(
                default="",
                help_text="\n            Describes the details of the offer.\n            <br>\n            Explain (when applicable):\n            <ul>\n                <li>\n                    what service is being provided\n                </li>\n                <li>\n                    what you need from the buyer (requirements, references, etc.)\n                </li>\n                <li>\n                    when a commission is considered finished\n                </li>\n            </ul>\n            ",
                max_length=4700,
                validators=[django.core.validators.MinLengthValidator(18)],
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="max_commissions_per_user",
            field=models.PositiveIntegerField(
                default=1,
                help_text="\n            Limits how many commissions a user can make on this offer.\n            <br>\n            Commission state does not matter, so if you reject a commission from a user, it still counts to this limit.\n            <br>\n            Self-managed commissions are not limited.\n            ",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Maximum Commissions per User",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="max_review_commissions",
            field=models.PositiveIntegerField(
                default=5,
                help_text="\n            The maximum number of commissions allowed to be in the review state.\n            <br>\n            Use this to prevent being overloaded with too many commission requests at a time for this offer.\n            <br>\n            Self-managed commissions are not limited by this, but contribute to the number of commissions in review.\n            ",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Maximum Commissions in Review",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="slots",
            field=models.PositiveIntegerField(
                default=3,
                help_text="\n            The maximum number of commissions you are willing to work on for this offer.\n            <br>\n            This is not a hard limit; it is used to communicate how many commissions you are willing to work.\n            ",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Slots",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="A thumbnail is optional, but it will be shown when users search for offers and when they visit this offer's page.",
                null=True,
                upload_to="",
                validators=[
                    furfolio.validators.validate_offer_thumbnail_aspect_ratio,
                    furfolio.validators.validate_offer_thumbnail_has_max_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Avatars are optional. Your avatar will be resized to 64 by 64 pixels.",
                upload_to="",
                validators=[
                    furfolio.validators.validate_profile_image_is_right_size,
                    furfolio.validators.validate_avatar_has_max_size,
                ],
            ),
        ),
    ]
