# Generated by Django 4.2.4 on 2023-11-22 22:13

from django.db import migrations, models
import furfolio.models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0063_alter_offer_cutoff_date_alter_offer_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="cutoff_date",
            field=models.DateTimeField(
                default=furfolio.models.seven_days_from_now,
                help_text="When your offer is no longer accepting commissions.",
            ),
        ),
    ]
