# Generated by Django 4.2.4 on 2023-12-28 00:22

from django.db import migrations, models
import furfolio.models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0064_alter_offer_cutoff_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="cutoff_date",
            field=models.DateTimeField(
                default=furfolio.models.seven_days_from_now,
                help_text='\n            When your offer is no longer accepting commissions.\n            <br>\n            <span class="text-danger">Note</span>: This cannot be changed after the offer is created. \n            ',
                verbose_name="Cutoff Time",
            ),
        ),
    ]
