# Generated by Django 4.2.7 on 2024-01-01 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import furfolio.models
import furfolio.validators


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0065_alter_offer_cutoff_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the chat room.", max_length=160
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="offer",
            name="cutoff_date",
            field=models.DateTimeField(
                default=furfolio.models.seven_days_from_now,
                help_text='\n            When your offer is no longer accepting commissions.\n            <br>\n            <span class="text-danger">Note</span>: This cannot be changed after the offer is created.\n            ',
                verbose_name="Cutoff Time",
            ),
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="furfolio.chat"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=1645)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        upload_to="",
                        validators=[
                            furfolio.validators.validate_commission_message_attachment_has_max_size
                        ],
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="furfolio.chat"
                    ),
                ),
            ],
        ),
    ]
