# Generated by Django 4.2.7 on 2024-01-02 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0067_commission_chat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommissionMessage",
        ),
    ]
