# Generated by Django 4.2.7 on 2024-01-09 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0075_commissioncreatednotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollowinguser",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
