# Generated by Django 4.2.7 on 2024-01-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0080_remove_commission_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionChat",
            fields=[
                (
                    "chat_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="furfolio.chat",
                    ),
                ),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="furfolio.commission",
                    ),
                ),
            ],
            bases=("furfolio.chat",),
        ),
    ]
