# Generated by Django 4.2.7 on 2024-01-12 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0081_commissionchat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="name",
        ),
    ]
