# Generated by Django 4.2.7 on 2024-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0084_supportticketchat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="This is how you will be refered to on this website.",
                max_length=42,
                unique=True,
            ),
        ),
    ]
