# Generated by Django 4.2.7 on 2024-01-29 00:30

from django.db import migrations

def add_support_moderators_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    
    support_mod_group = Group(name="support_mod")
    support_mod_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0086_alter_user_username"),
    ]

    operations = [
        migrations.RunPython(add_support_moderators_group),
    ]
