# Generated by Django 4.2.7 on 2024-01-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furfolio", "0089_supportticketstatenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipant",
            name="role",
            field=models.CharField(
                choices=[("BASIC", "Basic"), ("MANAGER", "Manager")],
                default="BASIC",
                max_length=7,
            ),
        ),
    ]
